"use strict";
const axios = require("axios");
const cheerio = require("cheerio");

const BASE = "https://demonicscans.org";
const IMAGE_HOSTS = new Set(["demonicscans.org", "www.demonicscans.org", "cdn.demoniclibs.com", "readermc.org", "mangareadon.org"]);
const PER_PAGE = 20;
const text = (v, f = "") => v === null || v === undefined ? f : (String(v).replace(/\s+/g, " ").trim() || f);
const cleanSlug = (v = "") => decodeURIComponent(String(v)).replace(/^https?:\/\/(?:www\.)?demonicscans\.org\/manga\//i, "").replace(/^\/+|\/+$/g, "").replace(/^manga\//i, "").split(/[?#]/)[0];
const imageUrl = (v = "") => { const x = String(v || "").trim().replace(/&amp;/g, "&"); return !x || /^data:|^blob:/i.test(x) ? "" : /^https?:\/\//i.test(x) ? x : `${BASE}/${x.replace(/^\/+/, "")}`; };
function headers(referer = `${BASE}/`) { return { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/132 Safari/537.36", Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", Referer: referer }; }
async function fetchPage(path, referer) { const r = await axios.get(path.startsWith("http") ? path : `${BASE}${path}`, { headers: headers(referer), timeout: 25000, responseType: "text", validateStatus: s => s >= 200 && s < 300 }); return r.data; }
const PUBLIC_API_BASE = (process.env.PUBLIC_API_BASE_URL || "https://api.ryukomik.web.id").replace(/\/+$/, "");
function base() { return PUBLIC_API_BASE; }
function proxy(v, req) { const url = imageUrl(v); return url ? `${base(req)}/demon/image?url=${encodeURIComponent(url)}` : ""; }
function rewrite(v, req) { if (Array.isArray(v)) return v.map(x => rewrite(x, req)); if (!v || typeof v !== "object") return v; const o = {}; for (const [k, x] of Object.entries(v)) o[k] = k === "images" && Array.isArray(x) ? x.map(i => proxy(i, req)).filter(Boolean) : ["image","thumbnail","cover"].includes(k) && typeof x === "string" ? proxy(x, req) : x && typeof x === "object" ? rewrite(x, req) : x; return o; }
function chapterKey(manga, chapter) { return `${manga}-${chapter}`; }
function chapterParts(key) { const m = String(key).match(/^(\d+)-(\d+)$/); return m ? { manga: m[1], chapter: m[2] } : null; }
function parseChapterLink($, el, manga) { const u = new URL($(el).attr("href") || "", BASE); const c = u.searchParams.get("chapter"), mid = u.searchParams.get("manga") || manga; if (!c || !mid) return null; return { title: text($(el).find(".ch-title").text(), text($(el).text()).match(/Chapter\s+[\d.]+/i)?.[0] || `Chapter ${c}`), slug: chapterKey(mid,c), link: `chapter/${manga}/${chapterKey(mid,c)}`, date: text($(el).find(".ch-date").text(), text($(el).text()).match(/\d{4}-\d{2}-\d{2}/)?.[0] || ""), time: "", locked: false }; }
function uniq(chapters) { const seen = new Set(); return chapters.filter(c => c?.slug && !seen.has(c.slug) && seen.add(c.slug)); }
function parseDetail(html, slug) { const $=cheerio.load(html); const first = $("a[href*='chaptered.php?manga=']").first().attr("href") || ""; const manga = new URL(first,BASE).searchParams.get("manga"); if (!manga) throw new Error("ID manga Demonic tidak ditemukan"); const chapters=uniq($("a[href*='chaptered.php?manga=']").map((_,e)=>parseChapterLink($,e,manga)).get()); const title=text($("h1").first().text(),text($("title").text())); const description=text($(".description,.manga-description,.summary").first().text(),$("meta[name='description']").attr("content")); return { manga, data:{title,thumbnail:imageUrl($("img[alt*='"+title.replace(/'/g,"\\'")+"']").first().attr("src") || $(".manga-info img").first().attr("src")),type:"comic",status:text($("body").text().match(/Status\s*(Ongoing|Completed|Hiatus)/i)?.[1],"Unknown"),Pengarang:text($("body").text().match(/Author\s*([^\n]+)/i)?.[1],"-"),Umur:"-",Konsep:"-",artist:"-",genres:$(".genres-list a,.genres-list").text().split(/[,\n]/).map(x=>text(x)).filter(Boolean),synopsis:description || "Tidak ada sinopsis.",info:"",total_chapter:chapters.length,chapters} }; }
async function detail(slug) { return { success:true, data:(await parseDetail(await fetchPage(`/manga/${encodeURIComponent(slug)}`),slug)).data }; }
function cardItems(html) { const $=cheerio.load(html), out=[]; $(".updates-element").each((_,e)=>{const c=$(e), a=c.find("a[href*='/manga/']").first(), slug=cleanSlug(a.attr("href"));if(!slug)return;const chapters=uniq(c.find("a[href*='chaptered.php?manga=']").map((__,x)=>parseChapterLink($,x,new URL(c.find("a[href*='chaptered.php?manga=']").first().attr("href")||"",BASE).searchParams.get("manga"))).get());out.push({source:"demon",title:text(a.attr("title"),text(a.text())),slug,image:imageUrl(c.find("img").first().attr("src")),detail_link:`${BASE}/manga/${slug}`,description:"",type_genre:"comic",info:chapters[0]?.date||"",chapter_awal:chapters.at(-1)?.title||"",chapter_terbaru:chapters[0]?.title||"",chapters});});return out; }
async function pustaka(page) { const data=cardItems(await fetchPage(page>1?`/lastupdates.php?page=${page}`:"/lastupdates.php")); if(!data.length) throw new Error("Data Demonic kosong");return {data,meta:{currentPage:page,totalPages:page,hasNextPage:data.length>=PER_PAGE}}; }
async function search(q) { const $=cheerio.load(await fetchPage(`/search.php?manga=${encodeURIComponent(q)}`)); const seen=new Set(); return $("a[href*='/manga/']").map((_,e)=>{const a=$(e),slug=cleanSlug(a.attr("href"));if(!slug||seen.has(slug))return null;seen.add(slug);return {title:text(a.attr("title"),text(a.text()).replace(/\s+\d+$/, "")),image:imageUrl(a.find("img").attr("src")||a.parent().find("img").first().attr("src")),detail_link:`${BASE}/manga/${slug}`,type_genre:"comic",update:"",rating:"0",slug};}).get().filter(Boolean); }
async function reader(seriesSlug, key) { const p=chapterParts(key);if(!p)throw new Error("Slug chapter Demonic tidak valid");const html=await fetchPage(`/chaptered.php?manga=${p.manga}&chapter=${p.chapter}`,`${BASE}/manga/${seriesSlug}`),$=cheerio.load(html);const images=[...new Set($("img.imgholder").map((_,e)=>imageUrl($(e).attr("src"))).get().filter(u=>u&&!/free_ads|logo/i.test(u)))];if(!images.length)throw new Error("Gambar chapter Demonic tidak ditemukan");const links=uniq($("a[href*='chaptered.php?manga=']").map((_,e)=>parseChapterLink($,e,p.manga)).get());const pos=links.findIndex(c=>c.slug===key);return {success:true,mangaId:seriesSlug,chapterSlug:key,currentChapter:text($("title").text().match(/Chapter\s+[\d.]+/i)?.[0],key),prev:pos>=0?links[pos+1]?.slug||null:null,next:pos>0?links[pos-1]?.slug||null:null,back_to_detail:seriesSlug,totalImages:images.length,images}; }
const page=v=>{const n=Number.parseInt(v,10);return Number.isInteger(n)&&n>=1?n:null;};
module.exports=function(app,{getCache,setCache,coalescedScrape,getImageCache,setImageCache}){
 app.get("/demon/image",async(req,res)=>{if(!req.query.url)return res.status(400).send("No URL provided");try{const u=imageUrl(decodeURIComponent(req.query.url)),p=new URL(u);if(p.protocol!=="https:"||!IMAGE_HOSTS.has(p.hostname))return res.status(400).send("URL gambar Demonic tidak valid");const cached=getImageCache(u);if(cached){return res.set("Content-Type",cached.contentType).set("Cache-Control","public, max-age=604800, s-maxage=604800, stale-while-revalidate=604800").send(cached.buffer)}const r=await axios.get(u,{headers:headers(BASE),responseType:"stream",timeout:25000});const chunks=[];r.data.on("data",c=>chunks.push(c));r.data.on("end",()=>{const buf=Buffer.concat(chunks);setImageCache(u,buf,r.headers["content-type"]||"image/jpeg");res.set("Content-Type",r.headers["content-type"]||"image/jpeg");res.set("Cache-Control","public, max-age=604800, s-maxage=604800, stale-while-revalidate=604800");res.send(buf)})}catch(e){res.status(e.response?.status||502).send("Gagal mengambil gambar Demonic")}});
 app.get("/demon/pustaka",async(req,res)=>{const p=page(req.query.page||1);if(!p)return res.status(400).json({success:false,message:"Page tidak valid"});const k=`demon:p:${p}`,c=getCache(k);if(c)return res.json(c);try{const r=await coalescedScrape(k,()=>pustaka(p)),o={success:true,source:"demonicscans.org",page:p,total:r.data.length,meta:r.meta,data:rewrite(r.data,req)};setCache(k,o,120);res.json(o)}catch(e){res.status(502).json({success:false,data:[],message:e.message})}});
 app.get("/demon/search",async(req,res)=>{const q=text(req.query.q),p=page(req.query.page||1);if(!q)return res.status(400).json({success:false,message:"Masukkan parameter ?q="});if(!p)return res.status(400).json({success:false,message:"Page tidak valid"});const k=`demon:s:${q}:${p}`,c=getCache(k);if(c)return res.json(c);try{const d=await coalescedScrape(k,()=>search(q));const o={success:true,query:q,meta:{currentPage:p,totalPages:p,hasNextPage:false},data:rewrite(d,req)};setCache(k,o,300);res.json(o)}catch(e){res.status(502).json({success:false,query:q,data:[],message:e.message})}});
 app.get("/demon/detail/:slug",async(req,res)=>{const s=cleanSlug(req.params.slug);if(!s)return res.status(400).json({success:false,message:"Slug tidak diberikan"});const k=`demon:d:${s}`,c=getCache(k);if(c)return res.json(c);try{const o=rewrite(await coalescedScrape(k,()=>detail(s)),req);setCache(k,o,900);res.json(o)}catch(e){res.status(502).json({success:false,message:e.message})}});
 app.get("/demon/chapter/:seriesSlug/:chapterSlug",async(req,res)=>{const s=cleanSlug(req.params.seriesSlug),ch=text(req.params.chapterSlug);if(!s||!ch)return res.status(400).json({success:false,message:"Slug chapter tidak lengkap"});const k=`demon:c:${s}:${ch}`,c=getCache(k);if(c)return res.json(c);try{const o=rewrite(await coalescedScrape(k,()=>reader(s,ch)),req);setCache(k,o,7200);res.json(o)}catch(e){res.status(502).json({success:false,message:e.message})}});
 console.log("Demon routes registered: /demon/pustaka, /demon/search, /demon/detail/:slug, /demon/chapter/:seriesSlug/:chapterSlug, /demon/image");
};
