"use strict";

const axios = require("axios");
const SITE = "https://qimanga.com";
const API = "https://api.qimanga.com/api/v1";
const IMAGE_HOSTS = new Set(["media.qimanga.com", "media.qimanhwa.com"]);
const PER_PAGE = 20;

const text = (v, f = "") => v === null || v === undefined ? f : (String(v).replace(/\s+/g, " ").trim() || f);
const stripHtml = (v, f = "") => text(String(v || "").replace(/<[^>]*>/g, " "), f);
const cleanSlug = (v = "") => String(v).trim().replace(/^https?:\/\/(?:www\.)?qimanga\.com\/series\//i, "").replace(/^\/+|\/+$/g, "").split(/[?#/]/)[0];
const normalizeImage = (v) => { const url = text(v); return !url || url.startsWith("data:") || url.startsWith("blob:") ? "" : /^https?:\/\//i.test(url) ? url : `${SITE}/${url.replace(/^\/+/, "")}`; };
const parsePage = (v) => { const page = Number.parseInt(v, 10); return Number.isInteger(page) && page >= 1 ? page : null; };

function headers(referer = `${SITE}/`) { return { Accept: "application/json, text/plain, */*", Origin: SITE, Referer: referer, "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/132.0.0.0 Safari/537.36" }; }
async function apiGet(path, params) { return (await axios.get(`${API}${path}`, { params, headers: headers(), timeout: 20000, validateStatus: (s) => s >= 200 && s < 300 })).data; }
function base(req) { const f = req.headers["x-forwarded-proto"]; return `${String(Array.isArray(f) ? f[0] : f || req.protocol || "http").split(",")[0].trim()}://${req.get("host")}`; }
function proxied(url, req) { const image = normalizeImage(url); return image ? `${base(req)}/qimanga/image?url=${encodeURIComponent(image)}` : ""; }
function rewrite(value, req) { if (Array.isArray(value)) return value.map((v) => rewrite(v, req)); if (!value || typeof value !== "object") return value; const out = {}; for (const [key, item] of Object.entries(value)) out[key] = key === "images" && Array.isArray(item) ? item.map((v) => typeof v === "string" ? proxied(v, req) : v).filter(Boolean) : ["image", "thumbnail", "cover", "chapter_thumbnail"].includes(key) && typeof item === "string" ? proxied(item, req) : item && typeof item === "object" ? rewrite(item, req) : item; return out; }
function timeAgo(value) { const d = new Date(value); if (!value || Number.isNaN(d.getTime())) return ""; const sec = Math.max(0, Math.floor((Date.now() - d.getTime()) / 1000)); for (const [n, l] of [[31536000,"tahun"],[2592000,"bulan"],[604800,"minggu"],[86400,"hari"],[3600,"jam"],[60,"menit"]]) if (sec >= n) return `${Math.floor(sec / n)} ${l} lalu`; return "baru saja"; }
function chapter(raw, seriesSlug) { const slug = text(raw?.slug), number = raw?.number; return { title: text(raw?.title, number !== undefined ? `Chapter ${number}` : "Chapter"), slug, link: slug ? `chapter/${seriesSlug}/${slug}` : "", date: timeAgo(raw?.createdAt), time: timeAgo(raw?.createdAt), locked: Boolean(raw?.requiresPurchase || raw?.price > 0 || raw?.isFree === false) }; }
function item(raw) { const slug = cleanSlug(raw?.slug); if (!slug) return null; const chapters = Array.isArray(raw?.chapters) ? raw.chapters.map((c) => chapter(c, slug)).filter((c) => c.slug) : []; return { source: "qimanga", title: text(raw?.title), slug, image: normalizeImage(raw?.cover), detail_link: `${SITE}/series/${slug}`, description: stripHtml(raw?.description), type_genre: text(raw?.type, "MANHWA").toLowerCase(), info: timeAgo(raw?.lastChapterAddedAt || raw?.createdAt), chapter_awal: chapters.at(-1)?.title || "", chapter_terbaru: chapters[0]?.title || "", chapters }; }
function meta(data, page, count) { const currentPage = Number(data?.current ?? data?.page ?? page), totalPages = Number(data?.totalPages ?? currentPage), totalItems = Number(data?.totalItems); return { currentPage: currentPage > 0 ? currentPage : page, totalPages: totalPages > 0 ? totalPages : page, ...(Number.isFinite(totalItems) ? { totalItems } : { hasNextPage: Boolean(data?.next) || count >= PER_PAGE }) }; }
async function allChapters(slug) { const first = await apiGet(`/series/${encodeURIComponent(slug)}/chapters`, { page: 1, perPage: 100, sort: "desc" }); const all = Array.isArray(first?.data) ? [...first.data] : []; for (let page = 2, max = Math.min(Number(first?.totalPages) || 1, 100); page <= max; page += 1) { const next = await apiGet(`/series/${encodeURIComponent(slug)}/chapters`, { page, perPage: 100, sort: "desc" }); all.push(...(next?.data || [])); } return [...new Map(all.map((c) => [c.slug, c])).values()]; }
async function pustaka(page, sort) { const sorts = { latest: "latest", newest: "latest", alphabet: "title", rating: "rating" }; const payload = await apiGet("/series", { page, perPage: PER_PAGE, sort: sorts[sort] || "latest" }); const data = (payload?.data || []).filter((x) => x?.type !== "NOVEL").map(item).filter(Boolean); if (!data.length) throw new Error("Data QiManga kosong"); return { data, meta: meta(payload, page, data.length) }; }
async function search(query, page) { const payload = await apiGet("/series/search", { q: query, page, perPage: PER_PAGE }); const data = (payload?.data || []).filter((x) => x?.type !== "NOVEL").map(item).filter(Boolean).map((x) => ({ title: x.title, image: x.image, detail_link: x.detail_link, type_genre: x.type_genre, update: x.chapter_terbaru, rating: "0", slug: x.slug })); return { data, meta: meta(payload, page, data.length) }; }
async function detail(slug) { const [series, raws] = await Promise.all([apiGet(`/series/${encodeURIComponent(slug)}`), allChapters(slug)]); const chapters = raws.map((c) => chapter(c, slug)).filter((c) => c.slug), genres = (series?.genres || []).map((g) => text(g?.name ?? g)).filter(Boolean); return { success: true, data: { title: text(series?.title), thumbnail: normalizeImage(series?.cover), type: text(series?.type, "MANHWA"), status: text(series?.status, "Unknown"), Pengarang: text(series?.author, "-"), Umur: "-", Konsep: text(series?.releaseDate, "-"), artist: text(series?.artist, "-"), genres, synopsis: stripHtml(series?.description, "Tidak ada sinopsis."), info: "", total_chapter: chapters.length, chapters } }; }
async function reader(seriesSlug, chapterSlug) { const raw = await apiGet(`/series/${encodeURIComponent(seriesSlug)}/chapters/${encodeURIComponent(chapterSlug)}`); if (raw?.requiresPurchase || raw?.price > 0 || raw?.isFree === false) return { success: false, locked: true, message: "Chapter premium QiManga tidak dapat diakses tanpa pembelian." }; const images = [...new Map((raw?.images || []).sort((a,b) => (a.order || 0) - (b.order || 0)).map((x) => { const u = normalizeImage(x?.url || x); return [u, u]; })).values()].filter(Boolean); if (!images.length) throw new Error("Gambar chapter QiManga tidak ditemukan"); return { success: true, mangaId: seriesSlug, chapterSlug, currentChapter: text(raw?.title, `Chapter ${raw?.number ?? ""}`.trim()), prev: raw?.navigation?.prev?.slug || null, next: raw?.navigation?.next?.slug || null, back_to_detail: seriesSlug, totalImages: images.length, images }; }

module.exports = function(app, { getCache, setCache, coalescedScrape }) {
  app.get("/qimanga/image", async (req, res) => { if (!req.query.url) return res.status(400).send("No URL provided"); try { const url = normalizeImage(decodeURIComponent(req.query.url)), parsed = new URL(url); if (parsed.protocol !== "https:" || !IMAGE_HOSTS.has(parsed.hostname)) return res.status(400).send("URL gambar QiManga tidak valid"); const image = await axios.get(url, { headers: headers(), responseType: "stream", timeout: 20000 }); res.set({ "Content-Type": image.headers["content-type"] || "image/jpeg", "Cache-Control": "public, max-age=31536000" }); image.data.pipe(res); } catch (error) { res.status(error.response?.status || 502).send("Gagal mengambil gambar QiManga"); } });
  app.get("/qimanga/pustaka", async (req, res) => { const page = parsePage(req.query.page || "1"); if (!page) return res.status(400).json({ success:false,message:"Page tidak valid" }); const sort = text(req.query.sort,"latest").toLowerCase(), key=`qimanga:pustaka:${sort}:${page}`, cached=getCache(key); if(cached)return res.json(cached); try { const r=await coalescedScrape(key,()=>pustaka(page,sort)), out={success:true,source:"qimanga.com",page,total:r.data.length,meta:r.meta,data:rewrite(r.data,req)}; setCache(key,out,120);res.json(out); } catch(error) { console.error(`[QiManga Pustaka Error] ${error.message}`);res.status(502).json({success:false,page,total:0,data:[],message:"Sumber QiManga tidak dapat diakses"}); } });
  app.get("/qimanga/search", async (req, res) => { const query=text(req.query.q),page=parsePage(req.query.page||"1"); if(!query)return res.status(400).json({success:false,message:"Masukkan parameter ?q="});if(!page)return res.status(400).json({success:false,message:"Page tidak valid"});const key=`qimanga:search:${query.toLowerCase()}:${page}`,cached=getCache(key);if(cached)return res.json(cached);try{const r=await coalescedScrape(key,()=>search(query,page)),out={success:true,query,meta:r.meta,data:rewrite(r.data,req)};setCache(key,out,300);res.json(out)}catch(error){console.error(`[QiManga Search Error] ${error.message}`);res.status(502).json({success:false,query,data:[],message:"Gagal mencari komik QiManga"})} });
  app.get("/qimanga/detail/:slug", async (req,res) => { const slug=cleanSlug(req.params.slug);if(!slug)return res.status(400).json({success:false,message:"Slug tidak diberikan!"});const key=`qimanga:detail:${slug}`,cached=getCache(key);if(cached)return res.json(cached);try{const out=rewrite(await coalescedScrape(key,()=>detail(slug)),req);setCache(key,out,900);res.json(out)}catch(error){console.error(`[QiManga Detail Error] ${error.message}`);res.status(502).json({success:false,message:"Gagal mengambil detail QiManga"})} });
  app.get("/qimanga/chapter/:seriesSlug/:chapterSlug", async (req,res) => { const seriesSlug=cleanSlug(req.params.seriesSlug),chapterSlug=text(req.params.chapterSlug);if(!seriesSlug||!chapterSlug)return res.status(400).json({success:false,message:"Slug chapter tidak lengkap!"});const key=`qimanga:chapter:${seriesSlug}:${chapterSlug}`,cached=getCache(key);if(cached)return res.json(cached);try{const r=await coalescedScrape(key,()=>reader(seriesSlug,chapterSlug)),out=r.success?rewrite(r,req):r;if(out.success)setCache(key,out,7200);res.status(out.success?200:403).json(out)}catch(error){console.error(`[QiManga Chapter Error] ${error.message}`);res.status(502).json({success:false,message:error.message})} });
  console.log("QiManga routes registered: /qimanga/image, /qimanga/pustaka, /qimanga/detail/:slug, /qimanga/chapter/:seriesSlug/:chapterSlug, /qimanga/search");
};
module.exports._test = { cleanSlug, normalizeImage, chapter, parsePage, meta };
